spring:
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest


logging:
  level:
    org: ERROR

server:
  port: 8080

student-api:
  queue: "student_queue"
  exchange : "student_exchange"
  routingKey: "student_routingKey"
  xmlPath : "D:\\tema\\student-api\\student-importer-service\\src\\main\\static\\pending\\student.xml"
  archivedDestination : "D:\\tema\\student-api\\student-importer-service\\src\\main\\static\\archived\\student.xml"
  errorDestination : "D:\\tema\\student-api\\student-importer-service\\src\\main\\static\\error\\student.xml"